[project]
name = "dmc-lp-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "pulp>=3.3.0",
    "streamlit>=1.50.0",
]
